// export const API_BASE_URL_1 = "https://localhost:55288/";
// export const API_BASE_URL = "https://localhost:55288/api/1";
// export const API_BASE_URL_IMG = "https://localhost:55288";
export const API_BASE_URL_1 = "https://api.hobyhub.com/";
export const API_BASE_URL = "https://api.hobyhub.com/api/1";
export const API_BASE_URL_IMG = "https://api.hobyhub.com";
export const GOOGLE_MAP_API_KEY = "AIzaSyBu5_sJSqh-SG1-GjuFsbG6KVuNzs6vuSA"; //mohammed
//export const GOOGLE_MAP_API_KEY = "AIzaSyBiXRza3cdC49oDky7hLyXPqkQhaNM4yts"; //hoby
// export const GOOGLE_MAP_API_KEY = "AIzaSyBR0YNTIOqZVKtIDG0Pjf-bkrJke_DtfBs"; //ali bhai